### ISSUE TITLE
User Auth Review

### ISSUE THREAD

**Issue by eric-to** [eric-to/everdeen#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] When errors are displayed, the input boxes should not move
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
  - [x] Errors should display for both `/signup` and`/login`.
  - [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Adequate and appropriate seeds
  - [x] Demo Login Works

**Comment by eric-to** [comment]
Errors move input boxes on the original website, although I'll restyle it on mine so that it doesn't.

**Comment by xnanodax** [comment]
Looks good! Great job :)
